apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-config
  namespace: travel-api
data:
  REDIS_HOST: "redis-service"
  DOTNET_URL: "http://dotnet-service:5000"
  NEXTJS_URL: "http://nextjs-service:3000"
